def save_portfolio_report(portfolio_report, table_name):
    fmt_str = """(
        {total_coins},
        {total_coins_change},
        {current_roi_btc},
        {current_roi_pct_btc},
        {current_roi_eth},
        {current_roi_pct_eth},
        {current_roi_usd},
        {current_roi_pct_usd},
        {est_btc},
        {est_btc_change_daily},
        {est_btc_pct_change_daily},
        {est_btc_change_weekly},
        {est_btc_pct_change_weekly},
        {est_eth},
        {est_eth_change_daily},
        {est_eth_pct_change_daily},
        {est_eth_change_weekly},
        {est_eth_pct_change_weekly},
        {est_usd},
        {est_usd_change_daily},
        {est_usd_pct_change_daily},
        {est_usd_change_weekly},
        {est_usd_pct_change_weekly},
    )"""
    columns = """
        total_coins,
        total_coins_change,
        current_roi_btc,
        current_roi_pct_btc,
        current_roi_eth,
        current_roi_pct_eth,
        current_roi_usd,
        current_roi_pct_usd,
        est_btc,
        est_btc_change_daily,
        est_btc_pct_change_daily,
        est_btc_change_weekly,
        est_btc_pct_change_weekly,
        est_eth,
        est_eth_change_daily,
        est_eth_pct_change_daily,
        est_eth_change_weekly,
        est_eth_pct_change_weekly,
        est_usd,
        est_usd_change_daily,
        est_usd_pct_change_daily,
        est_usd_change_weekly,
        est_usd_pct_change_weekly
    """
    values = fmt_str.format(**portfolio_report)
    query = """ INSERT INTO """ + table_name + """ (%(columns)s) VALUES %(values)s ; """
    return query, columns, values
